version: "3"

services:

  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api/app:/app

  web:
    build: ./web
    ports:
      - "8080:3000"
    volumes:
      - ./web/app/src:/app/src
      - ./web/app/public:/app/public
