version: "3.3"

services:

  api:
    build: ./api
    image: flavienb/icons-visualizer-api:develop
    restart: always
    volumes:
      - ./api/app:/app
      - ./icons:/icons:ro

  web:
    build: ./web
    image: flavienb/icons-visualizer-web:develop
    restart: always
    env_file:
      - .env
    volumes:
      - ./web/app:/app

  # We set-up an NGINX to have a unique endpoint for app & api
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: flavienb/icons-visualizer-nginx:develop
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/icons-visualizer.conf:/etc/nginx/conf.d/icons-visualizer.conf:ro
      - ./logs:/var/log/nginx
