apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: icons-visualizer
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: flavienb/icons-visualizer-api:latest
          name: api
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          env:
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  key: FLASK_ENV
                  name: env
            - name: USE_S3
              valueFrom:
                configMapKeyRef:
                  key: USE_S3
                  name: env
            - name: MINIO_IS_HTTPS
              valueFrom:
                configMapKeyRef:
                  key: MINIO_IS_HTTPS
                  name: env
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ENDPOINT
                  name: env
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ACCESS_KEY
                  name: env
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  key: MINIO_SECRET_KEY
                  name: env
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  namespace: icons-visualizer
  name: api
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: api
status:
  loadBalancer: {}
