apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: icons-visualizer
  name: minio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: scw-bssd-retain # Specific to Scaleway Kapsule
  resources:
    requests:
      storage: 10Gi
